### ISSUE TITLE
bug in doc/stable 

### ISSUE THREAD

**Issue by troussil** [DGtal-team/dgtal.github.io#14]
'stable' should be a copy of '1.2' but is not; some pages should be available in 'stable' folder but are not. 
For example, we can see https://dgtal.org/doc/1.2/moduleQuickHull.html
but not https://dgtal.org/doc/stable/moduleQuickHull.html.

**Comment by dcoeurjo** [comment]
👍 feel free to PR this repo

**Comment by dcoeurjo** [comment]
should be ok in #16
